# Generated by Django 5.0.1 on 2024-11-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("role", models.CharField(blank=True, max_length=7, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
