# Generated by Django 5.0.1 on 2024-11-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="is_authenticated",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="password_hash",
            field=models.CharField(default="defaultpassword", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("USER", "User"), ("MANAGER", "Manager"), ("ADMIN", "Admin")],
                default="USER",
                max_length=7,
            ),
        ),
    ]
