# Generated by Django 5.0.1 on 2024-12-03 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "roadmap_management",
            "0002_alter_roadmaps_options_alter_roadmaps_created_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-4", "GPT-4"),
                            ("gpt-4-turbo", "GPT-4 Turbo"),
                            ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                        ],
                        default="gpt-4",
                        max_length=50,
                    ),
                ),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=4096)),
                ("prompt_template", models.TextField()),
                ("token_count", models.IntegerField(blank=True, null=True)),
                ("generation_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_successful", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_configs",
                        to="roadmap_management.roadmaps",
                    ),
                ),
            ],
            options={
                "db_table": "roadmap_ai_configurations",
                "ordering": ["-created_at"],
            },
        ),
    ]
