# Generated by Django 5.0.1 on 2024-12-10 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roadmap_management", "0003_aiconfiguration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconfiguration",
            name="context_window",
            field=models.IntegerField(default=4096),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="frequency_penalty",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="presence_penalty",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="tech_analysis_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="top_p",
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name="GlobalAIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-4", "GPT-4"),
                            ("gpt-4-turbo", "GPT-4 Turbo"),
                            ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                        ],
                        default="gpt-4",
                        max_length=50,
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Valeur entre 0 et 1 pour contrôler la créativité",
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=4096,
                        help_text="Nombre maximum de tokens pour la réponse",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="Tu es un expert en création de roadmaps personnalisées...",
                        help_text="Prompt système par défaut pour la génération",
                    ),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_config_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration IA Globale",
                "verbose_name_plural": "Configuration IA Globale",
            },
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nom du Template"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "template_content",
                    models.TextField(verbose_name="Contenu du Template"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="Actif")),
                (
                    "token_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nombre de Tokens"
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Modèle Utilisé",
                    ),
                ),
                (
                    "generation_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Temps de Génération"
                    ),
                ),
                (
                    "technical_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Score Technique",
                    ),
                ),
                (
                    "error_logs",
                    models.TextField(
                        blank=True, null=True, verbose_name="Logs d'Erreurs"
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="Version")),
                (
                    "version_timestamp",
                    models.DateTimeField(auto_now=True, verbose_name="Date de Version"),
                ),
                (
                    "version_changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Changements de Version"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "version_author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur de la Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Prompt",
                "verbose_name_plural": "Templates de Prompt",
            },
        ),
    ]
