# Generated by Django 5.0.1 on 2024-12-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                (
                    "cache_type",
                    models.CharField(
                        choices=[
                            ("QUESTIONS", "Questions Statistics"),
                            ("RESPONSES", "Responses Statistics"),
                            ("ROADMAPS", "Roadmaps Statistics"),
                            ("USERS", "Users Statistics"),
                            ("DASHBOARD", "Dashboard Overview"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        help_text="Parameters used to generate this cache",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_cache",
                "indexes": [
                    models.Index(
                        fields=["cache_type", "expires_at"],
                        name="analytics_c_cache_t_3743ea_idx",
                    ),
                    models.Index(fields=["key"], name="analytics_c_key_af5a39_idx"),
                ],
            },
        ),
    ]
