# Generated by Django 5.0.1 on 2024-11-21 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("question_handling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Responses",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.JSONField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=False)),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("draft_data", models.JSONField(blank=True, null=True)),
                ("is_original", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        db_column="question_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question_handling.questions",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "responses",
            },
        ),
        migrations.CreateModel(
            name="ResponsesBackup",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.JSONField()),
                ("is_complete", models.BooleanField(default=False)),
                ("backup_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("version_index", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question_handling.questions",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to="response_management.responses",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "responses_backup",
                "ordering": ["backup_at"],
            },
        ),
    ]
